/**
 * Shared utility for downloading reports as text/PDF-like files.
 */
export function downloadReport(filename: string, content: string) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadCSV(filename: string, headers: string[], rows: string[][]) {
  const csvContent = [headers.join(","), ...rows.map(row => row.map(cell => `"${cell}"`).join(","))].join("\n");
  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function generateForensicReport(title: string, sections: { heading: string; content: string }[]): string {
  const divider = "═".repeat(60);
  const thinDivider = "─".repeat(60);
  const now = new Date().toLocaleString();
  
  let report = `${divider}\n`;
  report += `  AIVENTRA — FORENSIC INTELLIGENCE SYSTEM\n`;
  report += `  ${title}\n`;
  report += `${divider}\n\n`;
  report += `  Generated: ${now}\n`;
  report += `  Classification: RESTRICTED — LAW ENFORCEMENT ONLY\n`;
  report += `  System: AIVENTRA v2.0 (Gemma AI Engine)\n\n`;
  
  for (const section of sections) {
    report += `${thinDivider}\n`;
    report += `  ${section.heading.toUpperCase()}\n`;
    report += `${thinDivider}\n`;
    report += `${section.content}\n\n`;
  }
  
  report += `${divider}\n`;
  report += `  END OF REPORT — AIVENTRA FORENSIC SYSTEM\n`;
  report += `  This report was auto-generated by AIVENTRA AI.\n`;
  report += `  All findings must be verified by qualified personnel.\n`;
  report += `${divider}\n`;
  
  return report;
}
